services:
  postgres:
    image: postgres:15
    container_name: architrack-postgres
    environment:
      POSTGRES_DB: architrack
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - architrack-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: architrack-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"
    networks:
      - architrack-network

networks:
  architrack-network:
    driver: bridge